name: Amanz Bot

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  run-amanz-bot:
    runs-on: ubuntu-latest
    
    # Tambah ni penting
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Amanz Bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py

      - name: Commit last_link.txt if updated
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add last_link.txt
          
          if git diff --staged --quiet; then
            echo "✅ Tiada perubahan pada last_link.txt"
          else
            git commit -m "chore: update last sent Amanz link"
            git push
            echo "✅ last_link.txt telah diupdate"
          fi
