name: Amanz & Phys.org Bot

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  run-multi-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Multi Bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py

      # Bahagian akhir main.yml
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.txt
          if git diff --staged --quiet; then
            echo "✅ Tiada berita baru."
          else
            git commit -m "chore: update links [skip ci]"
            git pull --rebase origin main && git push origin main --force
